# Generated by Django 4.0.4 on 2022-05-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familiares_coder', '0004_contacto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacto',
            new_name='Mensaje',
        ),
    ]
